CREATE TABLE [dbo].[factresellersales] (

	[ProductKey] int NULL, 
	[OrderDateKey] int NULL, 
	[DueDateKey] int NULL, 
	[ShipDateKey] int NULL, 
	[ResellerKey] int NULL, 
	[EmployeeKey] int NULL, 
	[PromotionKey] int NULL, 
	[CurrencyKey] int NULL, 
	[SalesTerritoryKey] int NULL, 
	[SalesOrderNumber] varchar(8000) NULL, 
	[SalesOrderLineNumber] smallint NULL, 
	[RevisionNumber] smallint NULL, 
	[OrderQuantity] smallint NULL, 
	[UnitPrice] decimal(38,6) NULL, 
	[ExtendedAmount] decimal(38,6) NULL, 
	[UnitPriceDiscountPct] float NULL, 
	[DiscountAmount] float NULL, 
	[ProductStandardCost] decimal(38,6) NULL, 
	[TotalProductCost] decimal(38,6) NULL, 
	[SalesAmount] decimal(38,6) NULL, 
	[TaxAmt] decimal(38,6) NULL, 
	[Freight] decimal(38,6) NULL, 
	[CarrierTrackingNumber] varchar(8000) NULL, 
	[CustomerPONumber] varchar(8000) NULL, 
	[OrderDate] datetime2(6) NULL, 
	[DueDate] datetime2(6) NULL, 
	[ShipDate] datetime2(6) NULL
);